#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\DemoController::accueil
damier:
    path: /damier
    controller: App\Controller\DemoController::damier

message:
        path: /message
        controller: App\Controller\DemoController::message